name: attracting_particles
author: Dzenan Ridjanovic <dzenanr@gmail.com>
homepage: http://ondart.me/
version: 0.0.9
description: >
  There are some particles on the canvas which start attracting each other when
  they come close. They will start drawing lines between them as they come closer
  to each other. The opacity of the lines depends upon the distance between the
  corresponding particles. If the distance is larger, then the opacity will be
  lower.
dependencies:
  browser: any
